"""add role of User

Revision ID: 1f2af3589e3c
Revises: f807896a5384
Create Date: 2023-06-26 15:42:04.453465

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1f2af3589e3c'
down_revision = 'f807896a5384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE role AS ENUM('admin', 'moderator', 'user')")
    op.add_column('users',
                  sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True, default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.execute("DROP TYPE role")
    # ### end Alembic commands ###
